export const timeline = [
  {
    period: "July 2025 – Present",
    role: "Data Scientist",
    org: "Management Solutions",
    url: "https://www.managementsolutions.com/en/",
    location: "Bilbao, Basque Country, Spain",
    description:
      "Data Scientist embedded in a major international bank, focused on developing and analysing scoring models to support risk and business decision-making. Works on EDA, feature analysis, and Python-based analytics in cloud environments (Amazon SageMaker) across multiple portfolios. Supports data quality, governance initiatives, and process automation using SQL, VBA, and Excel.",
    tags: ["Python", "AWS SageMaker", "Amazon Athena", "SQL", "Machine Learning", "Scoring", "Data Mining"],
  },
  {
    period: "Sept 2024 – Dec 2024",
    role: "Junior Software Developer",
    org: "Sploro",
    url: "https://sploro.eu/",
    location: "Pamplona, Navarre, Spain",
    description:
      "Adapted the Django backend to support migration of the Kronis application frontend to Next.js. Implemented unit tests to ensure functionality, developed a web interface interacting with the API, and configured a local development/testing environment with Docker using PostgreSQL and Redis containers.",
    tags: ["Django", "Django REST", "Next.js", "Docker", "PostgreSQL", "Redis"],
  },
  {
    period: "June 2024 – Aug 2024",
    role: "Junior Systems Assistant",
    org: "CYC",
    url: "https://www.cyc.es/",
    location: "Pamplona, Navarre, Spain",
    description:
      "Worked in systems and IT operations managing infrastructure, devices, and cloud tools. Configured and troubleshot VPNs on iPads, set up video conferencing systems (Microsoft Teams + Yealink), managed secure sign-ins with Microsoft Authenticator and digital signage (Admira). Delivered Excel-based data reporting.",
    tags: ["IT Operations", "VPN", "Microsoft Teams", "Excel"],
  },
] as const;

export const education = [
  {
    period: "Sept 2021 – June 2025",
    degree: "BSc Computer Science: International Programme",
    org: "Universidad Pública de Navarra",
    location: "Pamplona, Spain",
    gpa: "7.43 / 10",
    description:
      "International Programme student in Computer Science, specialising in software development and actively involved in cybersecurity initiatives.",
    highlights: [
      "Bachelor's Thesis based on an internship as Junior Software Developer at Splorotech. Adapted the Django backend to support migration of the frontend to Next.js and implemented unit tests to ensure functionality.",
      "After the backend adjustments, developed a web interface interacting with the API. Configured the local development environment with Docker using PostgreSQL and Redis containers.",
    ],
    tags: [
      "Java", "Python", "JavaScript", "C", "R", "MATLAB",
      "SQL", "React.js", "Git", "CI/CD", "OOP", "Algorithms",
      "Docker", "Machine Learning", "Deep Learning",
      "Data Modelling", "Mathematics", "Problem Solving",
    ],
  },
  {
    period: "Jan 2025 – June 2025",
    degree: "Erasmus+ Exchange",
    org: "Laurea University of Applied Sciences",
    location: "Helsinki, Finland",
    gpa: null,
    description:
      "Semester abroad in Helsinki as part of the Erasmus+ programme, attending four courses across cloud, data, and software quality disciplines.",
    highlights: [
      "AWS Cloud: aligned with the AWS Certified Cloud Practitioner certification.",
      "Building an Online Shop: data analysis, financial reports, and decision-making tools for strategic business decisions in various contexts.",
      "Data-Driven Decision Making: planning, analysis, and decision-making tools for strategic planning; analysing financial statements and business reports to make informed decisions.",
      "Fundamentals of Software Testing: basics of QA, testing processes, test techniques, review methods, and test documentation.",
    ],
    tags: ["AWS", "Cloud", "Software Testing", "QA", "Data Analysis", "Business Analysis", "Erasmus+"],
  },
  {
    period: "Jan 2025 – Apr 2025",
    degree: "Applied Data Science Programme",
    org: "Zrive",
    location: "Remote",
    gpa: null,
    description:
      "15-week intensive programme designed for high-performing university students and young professionals who want to launch their careers as Data Scientists.",
    highlights: [
      "50+ hours of live online sessions (Monday and Wednesday evenings), three cohorts per year.",
      "Curriculum: Intro to Applied Data Science → DS Fundamentals (EDA, Statistical Learning, model fitting, model diagnostics, Business Translation, System Design) → Real-company project.",
      "Final project: real-world churn prediction case with Komorebi AI and Sumauto, from data preprocessing to business-oriented modelling.",
      "Two mock interviews guided by mentors from companies such as Vodafone and Revolut, plus 1-to-1 mentoring session.",
    ],
    tags: ["Python", "Scikit-learn", "FastAPI", "Statistics", "LLMs", "LLMOps", "AI", "Business Analysis"],
  },
  {
    period: "June 2024 – July 2024",
    degree: "Stock Market and Value Investing Seminar",
    org: "Universidad Francisco Marroquín",
    location: "Remote",
    gpa: null,
    description:
      "Intensive seminar on financial markets and value investing conducted by experts Gustavo Martínez, José Ruiz de Alda, and Juan Luis Fresneda.",
    highlights: [
      "Macroeconomics & Financial Markets: economic and market indicators, monetary policy, interest rates, economic cycles; introduction to equities, fixed income, derivatives, and currencies.",
      "Stock Market Analysis: Fundamental Analysis I & II, sector and company analysis covering holding, cyclical, and growth companies.",
      "Financial Strategies & Competitiveness: competitive advantages, financial derivatives and strategies, corporate operations, short selling, and special situations.",
    ],
    tags: ["Value Investing", "Finance", "Fundamental Analysis", "Macroeconomics", "Equities", "Derivatives"],
  },
] as const;

export const certifications = [
  {
    name: "C1 Advanced (CAE)",
    issuer: "Cambridge International Education",
    date: "Nov 2024",
    logo: "/logos/cambridge.svg",
    focus: "C1 Advanced English proficiency",
    pdf: "/certifications/c1-advanced-cae.pdf",
  },
  {
    name: "AWS Certified Cloud Practitioner",
    issuer: "Amazon Web Services",
    date: "Jan 2026",
    logo: "/logos/aws.svg",
    focus: "Cloud fundamentals, services, architecture",
    pdf: "/certifications/aws-certified-cloud-practitioner.pdf",
  },
  {
    name: "Machine Learning with Python",
    issuer: "IBM",
    date: "Mar 2026",
    logo: "/logos/ibm.svg",
    focus: "Supervised and unsupervised learning, model evaluation",
    pdf: "/certifications/machine-learning-with-python.pdf",
  },
  {
    name: "Claude Code in Action",
    issuer: "Anthropic",
    date: "Mar 2026",
    logo: "/logos/anthropic.svg",
    focus: "Agentic workflows, multi-agent orchestration, GitHub integration",
    pdf: "/certifications/claude-code-in-action.pdf",
  },
  {
    name: "Introduction to Subagents",
    issuer: "Anthropic",
    date: "Mar 2026",
    logo: "/logos/anthropic.svg",
    focus: "Subagent orchestration and agent pipelines",
    pdf: "/certifications/introduction-to-subagents.pdf",
  },
  {
    name: "Introduction to Agent Skills",
    issuer: "Anthropic",
    date: "Mar 2026",
    logo: "/logos/anthropic.svg",
    focus: "Claude Code skill development and automation",
    pdf: "/certifications/introduction-to-agent-skills.pdf",
  },
  {
    name: "Young Talent Navarre 2024",
    issuer: "ESIC Business & Marketing School",
    date: "June 2024",
    logo: "/logos/esic.svg",
    focus: "Leadership, emotional intelligence, public speaking",
    pdf: null,
  },
  {
    name: "Data Visualization with Python",
    issuer: "IBM",
    date: "Mar 2026",
    logo: "/logos/ibm.svg",
    focus: "Matplotlib, Seaborn, Plotly, dashboards",
    pdf: "/certifications/data-visualization-with-python.pdf",
  },
  {
    name: "Data Analysis with Python",
    issuer: "IBM",
    date: "Feb 2026",
    logo: "/logos/ibm.svg",
    focus: "NumPy, pandas, exploratory data analysis",
    pdf: "/certifications/data-analysis-with-python.pdf",
  },
  {
    name: "Databases and SQL for Data Science with Python",
    issuer: "IBM",
    date: "Feb 2026",
    logo: "/logos/ibm.svg",
    focus: "SQL, relational databases, Python integration",
    pdf: "/certifications/databases-and-sql-for-data-science-with-python.pdf",
  },
  {
    name: "Python for Data Science, AI & Development",
    issuer: "IBM",
    date: "Feb 2026",
    logo: "/logos/ibm.svg",
    focus: "Python programming, APIs, web scraping",
    pdf: "/certifications/python-for-data-science-ai-development.pdf",
  },
] as const;

export const skills = {
  "Data Science & ML": [
    "Python",
    "pandas",
    "scikit-learn",
    "XGBoost",
    "LightGBM",
    "PyTorch",
    "Statistics",
    "Data Mining",
  ],
  "Cloud & Infrastructure": [
    "AWS SageMaker",
    "Amazon Athena",
    "AWS",
    "Docker",
    "Git",
    "CI/CD",
  ],
  "APIs & Backend": [
    "FastAPI",
    "Django",
    "Django REST",
    "PostgreSQL",
    "Redis",
    "SQL",
    "REST APIs",
  ],
  "Frontend & Full-stack": [
    "Next.js",
    "React",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
  ],
  "Agentic & AI": [
    "Claude Code",
    "LLMOps",
    "LLMs",
    "Multi-agent orchestration",
  ],
  "Data & Automation": [
    "Excel",
    "VBA",
    "Process Automation",
    "Data Engineering",
  ],
} as const;
